// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package client

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (product_id, user_id, parent_id, content)
VALUES ($1, $2, $3, $4)
RETURNING id, product_id, user_id, parent_id, content, created_at, updated_at
`

type CreateCommentParams struct {
	ProductID uuid.UUID   `json:"product_id"`
	UserID    uuid.UUID   `json:"user_id"`
	ParentID  pgtype.UUID `json:"parent_id"`
	Content   string      `json:"content"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.ProductID,
		arg.UserID,
		arg.ParentID,
		arg.Content,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.UserID,
		&i.ParentID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments WHERE id = $1 AND user_id = $2
`

type DeleteCommentParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteComment(ctx context.Context, arg DeleteCommentParams) error {
	_, err := q.db.Exec(ctx, deleteComment, arg.ID, arg.UserID)
	return err
}

const deleteCommentVote = `-- name: DeleteCommentVote :exec
DELETE FROM comment_votes WHERE comment_id = $1 AND user_id = $2
`

type DeleteCommentVoteParams struct {
	CommentID uuid.UUID `json:"comment_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteCommentVote(ctx context.Context, arg DeleteCommentVoteParams) error {
	_, err := q.db.Exec(ctx, deleteCommentVote, arg.CommentID, arg.UserID)
	return err
}

const getCommentsByProductId = `-- name: GetCommentsByProductId :many
SELECT
    c.id,
    c.product_id,
    c.user_id,
    c.parent_id,
    c.content,
    c.created_at,
    c.updated_at,
    u.name AS author_name,
    u.image AS author_image,
    (SELECT COUNT(*) FROM comment_votes cv WHERE cv.comment_id = c.id AND cv.vote_type = 'like')::bigint AS likes,
    (SELECT COUNT(*) FROM comment_votes cv WHERE cv.comment_id = c.id AND cv.vote_type = 'dislike')::bigint AS dislikes
FROM comments c
JOIN users u ON c.user_id = u.id
WHERE c.product_id = $1
ORDER BY c.created_at ASC
`

type GetCommentsByProductIdRow struct {
	ID          uuid.UUID        `json:"id"`
	ProductID   uuid.UUID        `json:"product_id"`
	UserID      uuid.UUID        `json:"user_id"`
	ParentID    pgtype.UUID      `json:"parent_id"`
	Content     string           `json:"content"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	AuthorName  string           `json:"author_name"`
	AuthorImage pgtype.Text      `json:"author_image"`
	Likes       int64            `json:"likes"`
	Dislikes    int64            `json:"dislikes"`
}

func (q *Queries) GetCommentsByProductId(ctx context.Context, productID uuid.UUID) ([]GetCommentsByProductIdRow, error) {
	rows, err := q.db.Query(ctx, getCommentsByProductId, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCommentsByProductIdRow
	for rows.Next() {
		var i GetCommentsByProductIdRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.UserID,
			&i.ParentID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorName,
			&i.AuthorImage,
			&i.Likes,
			&i.Dislikes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommentsByProductIdWithUserVote = `-- name: GetCommentsByProductIdWithUserVote :many
SELECT
    c.id,
    c.product_id,
    c.user_id,
    c.parent_id,
    c.content,
    c.created_at,
    c.updated_at,
    u.name AS author_name,
    u.image AS author_image,
    (SELECT COUNT(*) FROM comment_votes cv WHERE cv.comment_id = c.id AND cv.vote_type = 'like')::bigint AS likes,
    (SELECT COUNT(*) FROM comment_votes cv WHERE cv.comment_id = c.id AND cv.vote_type = 'dislike')::bigint AS dislikes,
    COALESCE((SELECT cv.vote_type FROM comment_votes cv WHERE cv.comment_id = c.id AND cv.user_id = $2), '')::text AS user_vote
FROM comments c
JOIN users u ON c.user_id = u.id
WHERE c.product_id = $1
ORDER BY c.created_at ASC
`

type GetCommentsByProductIdWithUserVoteParams struct {
	ProductID uuid.UUID `json:"product_id"`
	UserID    uuid.UUID `json:"user_id"`
}

type GetCommentsByProductIdWithUserVoteRow struct {
	ID          uuid.UUID        `json:"id"`
	ProductID   uuid.UUID        `json:"product_id"`
	UserID      uuid.UUID        `json:"user_id"`
	ParentID    pgtype.UUID      `json:"parent_id"`
	Content     string           `json:"content"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	AuthorName  string           `json:"author_name"`
	AuthorImage pgtype.Text      `json:"author_image"`
	Likes       int64            `json:"likes"`
	Dislikes    int64            `json:"dislikes"`
	UserVote    string           `json:"user_vote"`
}

func (q *Queries) GetCommentsByProductIdWithUserVote(ctx context.Context, arg GetCommentsByProductIdWithUserVoteParams) ([]GetCommentsByProductIdWithUserVoteRow, error) {
	rows, err := q.db.Query(ctx, getCommentsByProductIdWithUserVote, arg.ProductID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCommentsByProductIdWithUserVoteRow
	for rows.Next() {
		var i GetCommentsByProductIdWithUserVoteRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.UserID,
			&i.ParentID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorName,
			&i.AuthorImage,
			&i.Likes,
			&i.Dislikes,
			&i.UserVote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCommentVote = `-- name: UpsertCommentVote :one
INSERT INTO comment_votes (comment_id, user_id, vote_type)
VALUES ($1, $2, $3)
ON CONFLICT (comment_id, user_id)
DO UPDATE SET vote_type = $3
RETURNING id, comment_id, user_id, vote_type, created_at
`

type UpsertCommentVoteParams struct {
	CommentID uuid.UUID `json:"comment_id"`
	UserID    uuid.UUID `json:"user_id"`
	VoteType  string    `json:"vote_type"`
}

func (q *Queries) UpsertCommentVote(ctx context.Context, arg UpsertCommentVoteParams) (CommentVote, error) {
	row := q.db.QueryRow(ctx, upsertCommentVote, arg.CommentID, arg.UserID, arg.VoteType)
	var i CommentVote
	err := row.Scan(
		&i.ID,
		&i.CommentID,
		&i.UserID,
		&i.VoteType,
		&i.CreatedAt,
	)
	return i, err
}
