// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package client

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID        uuid.UUID        `json:"id"`
	Name      string           `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Product struct {
	ID          uuid.UUID        `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	Price       int64            `json:"price"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type ProductImage struct {
	ID        uuid.UUID        `json:"id"`
	ProductID int64            `json:"product_id"`
	ImageUrl  string           `json:"image_url"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type ProductsCategory struct {
	ID         uuid.UUID        `json:"id"`
	ProductID  uuid.UUID        `json:"product_id"`
	CategoryID uuid.UUID        `json:"category_id"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}
